spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "815280219004-i1gmefi230vgamrllv4h7v1vmnrq518d.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "http://localhost:8001/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: profile, email
          kakao:
            client-id: "8dd8993cb31f34f9f644d8919819b1cb"
            redirect-uri: "http://localhost:8001/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
          naver:
            client-id: "UyPUhKnygfDQ8hZKNmtd"
            client-secret: "prAX0zNARo"
            redirect-uri: "http://localhost:8001/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name
            client-name: Naver
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
            token_uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response